# Generated by Django 5.2.3 on 2025-07-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['expires_at', 'used'], name='api_downloa_expires_95fd68_idx'),
        ),
    ]
